config/routes.rb
Tauevarsel::Application.routes.draw do
  resources :street_events

  root :to => 'street_events#index'

end

app/models/street_event.rb
# == Schema Information
#
# Table name: street_events
#
#  id          :integer         not null, primary key
#  street      :string(255)
#  stretch     :string(255)
#  date        :date
#  time_of_day :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class StreetEvent < ActiveRecord::Base
  validates :street, presence: true
  validates :stretch, presence: true
  validates :date, presence: true

  def to_s
    "#{street}, stretch: #{stretch}, date: #{date}, time_of_day: #{time_of_day}"
  end

  def self.search(search)
    if search
      where('date = ?', "#{search}")
    else
      scoped
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/street_events_controller.rb
class StreetEventsController < ApplicationController
  # GET /street_events
  # GET /street_events.json
  def index
    @street_events = StreetEvent.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @street_events }
    end
  end

  # GET /street_events/1
  # GET /street_events/1.json
  def show
    @street_event = StreetEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @street_event }
    end
  end

  # GET /street_events/new
  # GET /street_events/new.json
  def new
    @street_event = StreetEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @street_event }
    end
  end

  # GET /street_events/1/edit
  def edit
    @street_event = StreetEvent.find(params[:id])
  end

  # POST /street_events
  # POST /street_events.json
  def create
    @street_event = StreetEvent.new(params[:street_event])

    respond_to do |format|
      if @street_event.save
        format.html { redirect_to @street_event, notice: 'Street event was successfully created.' }
        format.json { render json: @street_event, status: :created, location: @street_event }
      else
        format.html { render action: "new" }
        format.json { render json: @street_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /street_events/1
  # PUT /street_events/1.json
  def update
    @street_event = StreetEvent.find(params[:id])

    respond_to do |format|
      if @street_event.update_attributes(params[:street_event])
        format.html { redirect_to @street_event, notice: 'Street event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @street_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /street_events/1
  # DELETE /street_events/1.json
  def destroy
    @street_event = StreetEvent.find(params[:id])
    @street_event.destroy

    respond_to do |format|
      format.html { redirect_to street_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/street_events_helper.rb
module StreetEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tauevarsel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/street_events/_form.html.erb
<%= form_for(@street_event) do |f| %>
  <% if @street_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@street_event.errors.count, "error") %> prohibited this street_event from being saved:</h2>

      <ul>
      <% @street_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :stretch %><br />
    <%= f.text_field :stretch %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time_of_day %><br />
    <%= f.text_field :time_of_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/street_events/edit.html.erb
<h1>Editing street_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @street_event %> |
<%= link_to 'Back', street_events_path %>

app/views/street_events/index.html.erb
<h1>Listing street_events</h1>
<%= form_tag street_events_path, method: 'get' do %>
<p>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "search", name: nil %>
</p>
<% end %>

<table>
  <tr>
    <th>Street</th>
    <th>Stretch</th>
    <th>Date</th>
    <th>Time of day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @street_events.each do |street_event| %>
  <tr>
    <td><%= street_event.street %></td>
    <td><%= street_event.stretch %></td>
    <td><%= street_event.date %></td>
    <td><%= street_event.time_of_day %></td>
    <td><%= link_to 'Show', street_event %></td>
    <td><%= link_to 'Edit', edit_street_event_path(street_event) %></td>
    <td><%= link_to 'Destroy', street_event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Street event', new_street_event_path %>

app/views/street_events/new.html.erb
<h1>New street_event</h1>

<%= render 'form' %>

<%= link_to 'Back', street_events_path %>

app/views/street_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street:</b>
  <%= @street_event.street %>
</p>

<p>
  <b>Stretch:</b>
  <%= @street_event.stretch %>
</p>

<p>
  <b>Date:</b>
  <%= @street_event.date %>
</p>

<p>
  <b>Time of day:</b>
  <%= @street_event.time_of_day %>
</p>


<%= link_to 'Edit', edit_street_event_path(@street_event) %> |
<%= link_to 'Back', street_events_path %>